substitutions:
  _PROJECT: "cloudside-academy"
  _REGION: "us-central1"
  _ZONE: "us-central1-a"
  _MIG_NAME: "my-mig"
  _TEMPLATE_PREFIX: "myapp-template"

steps:
# Step 1: Create instance template
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'create-instance-template'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      echo "Project: ${_PROJECT}"

      # Generate unique template name using build ID or commit SHA
      SHORT_SHA="${SHORT_SHA:-${BUILD_ID}}"
      _TEMPLATE_NAME="${_TEMPLATE_PREFIX}-${SHORT_SHA}"
      echo "Creating instance template: ${_TEMPLATE_NAME}"

      gcloud compute instance-templates create "${_TEMPLATE_NAME}" \
        --project="${_PROJECT}" \
        --machine-type=e2-medium \
        --metadata-from-file=startup-script=startup.sh \
        --tags=http-server \
        --quiet

      # Save the name for next step
      echo "${_TEMPLATE_NAME}" > /workspace/_TEMPLATE_NAME.txt

# Step 2: Rolling update of the MIG using new template
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'rolling-update'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      _TEMPLATE_NAME=$(cat /workspace/_TEMPLATE_NAME.txt)
      echo "Starting rolling update for MIG ${_MIG_NAME} using template ${_TEMPLATE_NAME}"

      gcloud compute instance-groups managed rolling-action start-update "${_MIG_NAME}" \
        --project="${_PROJECT}" \
        --region="${_REGION}" \
        --version=template="${_TEMPLATE_NAME}" \
        --max-surge=1 \
        --max-unavailable=0 \
        --type=proactive \
        --quiet

timeout: 1200s


