substitutions:
  _PROJECT: "cloudside-academy"
  _ZONE: "us-central1-a"
  _MIG_NAME: "my-mig"
  _TEMPLATE_PREFIX: "myapp-template"
  _BUILD_ID_RAW: ${BUILD_ID}

steps:
# Step 1: Create new instance template
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'create-instance-template'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      
      # 1. GENERATE UNIQUE, LOWERCASE TEMPLATE NAME
      # Use SHORT_SHA if available, otherwise fall back to the guaranteed unique BUILD_ID.
      # Convert to lowercase for GCP naming compliance.
      UNIQUE_ID=$(echo "${_BUILD_ID_RAW}" | tr '[:upper:]' '[:lower:]')
      _TEMPLATE_NAME="${_TEMPLATE_PREFIX}-${UNIQUE_ID}"
      
      echo "Generated Template Name: ${_TEMPLATE_NAME}"
      
      # 2. CREATE INSTANCE TEMPLATE
      gcloud compute instance-templates create "${_TEMPLATE_NAME}" \
        --project="${_PROJECT}" \
        --machine-type=e2-medium \
        --metadata-from-file startup-script=startup.sh \
        --tags=http-server \
        --boot-disk-size=20GB \
        --boot-disk-type=pd-balanced \
        --image-family=ubuntu-2204-lts \
        --image-project=ubuntu-os-cloud \
        --quiet

      # 3. Save template name for the next step
      echo "${_TEMPLATE_NAME}" > /workspace/_TEMPLATE_NAME.txt

# Step 2: Rolling update the MIG for zero-downtime
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'rolling-update'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      _TEMPLATE_NAME=$(cat /workspace/_TEMPLATE_NAME.txt)
      echo "Starting rolling update for MIG ${_MIG_NAME} using template ${_TEMPLATE_NAME}"

      # max-unavailable=0: New instance must be healthy before old one is deleted (Zero Downtime).
      # max-surge=1: Allows one extra instance to spin up for the swap.
      gcloud compute instance-groups managed rolling-action start-update "${_MIG_NAME}" \
        --project="${_PROJECT}" \
        --zone="${_ZONE}" \
        --version=template="${_TEMPLATE_NAME}" \
        --max-surge=1 \
        --max-unavailable=0 \
        --type=proactive \
        --quiet
