substitutions:
  _PROJECT: "cloudside-academy"
  _ZONE: "us-central1-a"
  _MIG_NAME: "my-mig"
  _TEMPLATE_PREFIX: "myapp-template"

steps:
# Step 1: Create new instance template (Ubuntu-based)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'create-instance-template'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      
      # Use SHORT_SHA if available, otherwise fall back to BUILD_ID
      # This ensures the name is NEVER empty.
      _UNIQUE_ID="${SHORT_SHA:-$BUILD_ID}"
      _TEMPLATE_NAME="${_TEMPLATE_PREFIX}-${_UNIQUE_ID}"
      
      echo "Creating instance template: ${_TEMPLATE_NAME} in project ${_PROJECT}"

      # Create instance template using Ubuntu 22.04
      gcloud compute instance-templates create "${_TEMPLATE_NAME}" \
        --project="${_PROJECT}" \
        --machine-type=e2-medium \
        --metadata-from-file startup-script=startup.sh \
        --tags=http-server \
        --boot-disk-size=20GB \
        --boot-disk-type=pd-balanced \
        --image-family=ubuntu-2204-lts \
        --image-project=ubuntu-os-cloud \
        --quiet

      # Save template name for next step
      echo "${_TEMPLATE_NAME}" > /workspace/_TEMPLATE_NAME.txt

# Step 2: Rolling update the MIG
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'rolling-update'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      _TEMPLATE_NAME=$(cat /workspace/_TEMPLATE_NAME.txt)
      echo "Starting rolling update for MIG ${_MIG_NAME} using template ${_TEMPLATE_NAME}"

      # Perform rolling update
      # NOTE: Added --project flag
      gcloud compute instance-groups managed rolling-action start-update "${_MIG_NAME}" \
        --project="${_PROJECT}" \
        --zone="${_ZONE}" \
        --version=template="${_TEMPLATE_NAME}" \
        --max-surge=1 \
        --max-unavailable=0 \
        --type=proactive \
        --quiet

timeout: 1200s
